version: "3.9"
services:
  # configuracion del servidor alpine
  java_app:
    #container_name: java_app
    image: mibedelia:1.0
    ports:
      - "8080:8080"
    build: .
    links:
      - mysql
      - redis
    environment:
      - MYSQL_DRIVER=com.mysql.cj.jdbc.Driver
      - MYSQL_URL=jdbc:mysql://mysql:3306/prototipo2
      - MYSQL_USER=uMysql
      - MYSQL_PASSWORD=admin
      - HIBERNATE_DDL_AUTO=update
      - HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect #org.hibernate.dialect.MySQL57Dialect
      - HIBERNATE_NAMING_STRATEGY=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      - MYSQL_DATABASE=mysql
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TIMEOUT=1000
      - REDIS_MAX_ACTIVE=128
      - FIREBASE_TYPE=service_account
      - FIREBASE_PROJECT_ID=prototipo1-1e6c8
      - FIREBASE_PRIVATE_KEY_ID=60a94a1f96f374c26c061bed6fd5e3a359532db0
      - FIREBASE_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQClu3ARRUq0YML6\nthHKdHizH6kjRwTK8z7nUJRS0CtiRhdkDi6kA8kFJCMampcWLFmgmJrEyzNH26Sp\nskHygaUEJdsl9PhC/HEaLfapQwqZ7cXIdFKiRGNbKh3YvS/BYhUAT/QAnVREmsbR\n0ahRxk5VW9WS59MYWCffWNPfvCjIpIsrZYpNtW00/46ERpenAp9Hc2fUhnwF78KY\ngAcX2fohzKxsWlvRVumoKwTjzouLuqoh80bQgFepCyn7jBFJXDSLdUCqxanYFMoI\nusS42evQ3GWHocJ1v2BNs0qk5QnWEKZo0zEn+05ZG/GMa5A+digAR2OVrLEma6PK\ne+JOW4LnAgMBAAECggEANZnlqPBMNQKGjSeNoXkCAIzg2zQA7NK3KYD6N750CZi5\nv/aGRy2iOjNx1wzgiJ9XbYVtqPA/aaI0I14vzgr4H9tOgXw1PxT+T4VGHYA9UYOB\nUE+u2iRcLgP1G0A0zcq3GB7Dv98iff3BB+NTGP+WHi1Rae3obBs26hmEjPwCBMIN\nhhATchKXTa5i/6DvkGREDz4owRdphPMG+hpwGKZiNj3RydOyyKdiTX9uhYxWeTPA\nJ8FNEJ3+4lvK1adO7u3Limi7xkD+cNyG2HqVFvg5R6S1NR47Y82TLXB4SpgIwsiU\nSqIQrr/FAC2t0JlVIwd70ouZpoRLWfe1+Svl7McYwQKBgQDY73g1HVkQq7fhh9IH\nFZiJxPXNoxSgLXFXwEFAr5kFmZQBSUH/GQi+P4D5zFvLtNvRgUWdn42/YB1pVf12\nrOy/1sybCAnEQWrWwboZob0yaWpw9RBZBI+s7P3+OK8f8xE/w2i+uaqFsZ3XnIoB\nfmJB5pI+TzytuRn59YtPCSgb+QKBgQDDk4s+Q3ej/CSkXMnLiit3rwGvRArgYe6Y\nrZ4ppiiSZ6jMSF+QssWPA/aRVgZW10dHN65TzXA1oSkcwiGbdCKcj0+hvBaFFswP\nuGtqrEfc6g3YPX/FsQq074UQMLAA2UVd0JPPOf1B0aK+y4Ng5hdLYlN1WWZ5OvEj\nhDzeh9uN3wKBgQDKuZ6gJDjjN1WzUPWY4TmXJZR/AvN3bIAK/QL9rBtX/FkvioI+\nHerpvvaMecke6HizpBamYkBYoz1Y/p7KlHb6H4U9K5nU6T0qTAfZhCgGQDTUMm+A\ngJ6zfxUsyVP+i2uHJtlvwpn0LjPPFd5x3uV7qDjqOan+vofj6u6wgWIWIQKBgFQc\n7rP2nEwAs1mlNny9jfhJYjYY03yxYcZ0VSOgfK6KuoQxVDiNSn45vB/BmbRbniI5\nBlawcmP+Tgo6S+3pwsEGub7bf+v5ZAYW0MvuEHIoj4/C02MYw3wRz26pIekbiMPS\nYt+rFwrpuE7KhFR2YOpg/Xfo3TOib/dQdkVWtMyNAoGAJjRrg4i/OUZ1UB9bl4Ug\nwo9dR8zN23PPcKCN1XqlBgH8Ye7vmB46egc3F1k4N2l6Jk3mVmx3VbGXkSyL6rXR\n26IvB4L/ZeWO3Y/aY72iVIO2dgMXZQNh4kV4rEXkdSm9Acu235DrxEvQgklMnt95\nP3lZE3klmcLkutwywxL5RMA=\n-----END PRIVATE KEY-----\n
      - FIREBASE_CLIENT_EMAIL=firebase-adminsdk-to6qo@prototipo1-1e6c8.iam.gserviceaccount.com
      - FIREBASE_CLIENT_ID=113205316301667251100
      - FIREBASE_AUTH_URI=https://accounts.google.com/o/oauth2/auth
      - FIREBASE_TOKEN_URI=https://oauth2.googleapis.com/token
      - FIREBASE_AUTH_PROVIDER_X509_CERT_URL=https://www.googleapis.com/oauth2/v1/certs
      - FIREBASE_CLIENT_X509_CERT_URL=https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-to6qo%40prototipo1-1e6c8.iam.gserviceaccount.com
      - FIREBASE_UNIVERSE_DOMAIN=googleapis.com
    depends_on:
      - mysql
      - redis
    networks:
      - miredDocker

  mysql:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prototipo2
      MYSQL_USER: uMysql
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./databases/mysqldata:/var/lib/mysql
      - ./logs/mariadb:/var/log/mysql
    networks:
      - miredDocker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin
    depends_on:
      - mysql
    networks:
      - miredDocker

  redis:
    hostname: redis
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - miredDocker

networks:
  miredDocker:
    driver: bridge